#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { collinearOverlapLength, polylineLength, rectOf, segmentIntersectsRect, segmentsFromPoints, segmentsIntersect } from './geometry.mjs';
function readJson(filePath) { return JSON.parse(fs.readFileSync(filePath, 'utf8')); }
function writeJson(filePath, data) { fs.mkdirSync(path.dirname(filePath), { recursive: true }); fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`); }
function center(el) { return { x: el.x + el.width / 2, y: el.y + el.height / 2 }; }
function clamp(value, min, max) { return Math.max(min, Math.min(max, value)); }
function metaOf(el) { return el.customData?.excalidrawSkill ?? {}; }
function sideFor(from, to, hint = 'auto') { if (['right','left','up','down'].includes(hint)) return hint; const a = center(from); const b = center(to); if (Math.abs(b.x - a.x) >= Math.abs(b.y - a.y)) return b.x >= a.x ? 'right' : 'left'; return b.y >= a.y ? 'down' : 'up'; }
function opposite(side) { return ({ right: 'left', left: 'right', up: 'down', down: 'up' })[side]; }
function anchor(node, side, offset = 0) { if (side === 'right') return { x: node.x + node.width, y: clamp(node.y + node.height / 2 + offset, node.y + 12, node.y + node.height - 12) }; if (side === 'left') return { x: node.x, y: clamp(node.y + node.height / 2 + offset, node.y + 12, node.y + node.height - 12) }; if (side === 'down') return { x: clamp(node.x + node.width / 2 + offset, node.x + 12, node.x + node.width - 12), y: node.y + node.height }; return { x: clamp(node.x + node.width / 2 + offset, node.x + 12, node.x + node.width - 12), y: node.y }; }
function dedupe(points) { return points.filter((point, index) => index === 0 || point.x !== points[index - 1].x || point.y !== points[index - 1].y); }
function sceneBounds(nodes) { const values = [...nodes.values()]; return { left: Math.min(...values.map((n) => n.x)), right: Math.max(...values.map((n) => n.x + n.width)), top: Math.min(...values.map((n) => n.y)), bottom: Math.max(...values.map((n) => n.y + n.height)) }; }
function pointOutward(point, side, distance) { if (side === 'right') return { x: point.x + distance, y: point.y }; if (side === 'left') return { x: point.x - distance, y: point.y }; if (side === 'down') return { x: point.x, y: point.y + distance }; return { x: point.x, y: point.y - distance }; }
function faceAligned(start, end, sourceSide, targetSide) { if ((sourceSide === 'down' && targetSide === 'up') || (sourceSide === 'up' && targetSide === 'down')) return Math.abs(start.x - end.x) < 1e-9; if ((sourceSide === 'right' && targetSide === 'left') || (sourceSide === 'left' && targetSide === 'right')) return Math.abs(start.y - end.y) < 1e-9; return false; }
function candidates(start, end, sourceSide, targetSide, bounds, laneOffset) {
  const result = []; const clearance = 36 + Math.abs(laneOffset); const startStub = pointOutward(start, sourceSide, clearance); const endStub = pointOutward(end, targetSide, clearance);
  if (faceAligned(start, end, sourceSide, targetSide)) result.push([start, end]);
  const sourceVertical = sourceSide === 'up' || sourceSide === 'down'; const targetVertical = targetSide === 'up' || targetSide === 'down';
  if (sourceVertical && targetVertical) {
    const middleY = (start.y + end.y) / 2 + laneOffset;
    result.push(dedupe([start, { x: start.x, y: middleY }, { x: end.x, y: middleY }, end]));
    for (const bypassX of [bounds.left - 70 - Math.abs(laneOffset), bounds.right + 70 + Math.abs(laneOffset)]) result.push(dedupe([start, startStub, { x: bypassX, y: startStub.y }, { x: bypassX, y: endStub.y }, endStub, end]));
  } else if (!sourceVertical && !targetVertical) {
    const middleX = (start.x + end.x) / 2 + laneOffset;
    result.push(dedupe([start, { x: middleX, y: start.y }, { x: middleX, y: end.y }, end]));
    for (const bypassY of [bounds.top - 70 - Math.abs(laneOffset), bounds.bottom + 70 + Math.abs(laneOffset)]) result.push(dedupe([start, startStub, { x: startStub.x, y: bypassY }, { x: endStub.x, y: bypassY }, endStub, end]));
  } else {
    if (sourceVertical) result.push(dedupe([start, startStub, { x: endStub.x, y: startStub.y }, endStub, end]));
    else result.push(dedupe([start, startStub, { x: startStub.x, y: endStub.y }, endStub, end]));
  }
  return result;
}
function scoreRoute(points, obstacles, existingSegments) { const segments = segmentsFromPoints(points); let nodeHits = 0; let crossings = 0; let overlapLength = 0; for (const segment of segments) { nodeHits += obstacles.filter((rect) => segmentIntersectsRect(segment, rect)).length; for (const other of existingSegments) { if (segmentsIntersect(segment, other, { includeEndpoints: false })) crossings += 1; overlapLength += collinearOverlapLength(segment, other); } } return [nodeHits, overlapLength > 8 ? 1 : 0, overlapLength, crossings, Math.max(0, points.length - 2), polylineLength(points)]; }
function compareScore(first, second) { for (let index = 0; index < Math.max(first.length, second.length); index += 1) { const delta = (first[index] ?? 0) - (second[index] ?? 0); if (delta !== 0) return delta; } return 0; }
function edgeSpecMap(spec) { return new Map((spec?.edges ?? []).map((edge) => [edge.semanticId ?? `${edge.from}_to_${edge.to}`, edge])); }
function primaryPairs(spec) { const ids = spec?.layout?.primaryFlow ?? []; const pairs = new Set(); for (let i = 0; i < ids.length - 1; i += 1) pairs.add(`${ids[i]}->${ids[i + 1]}`); return pairs; }
function unifiedPortOffsets(edges, nodes, specs) {
  const groups = new Map(); const edgeSides = new Map();
  for (const edge of edges) { const meta = metaOf(edge); const from = nodes.get(meta.from); const to = nodes.get(meta.to); if (!from || !to) continue; const sourceSide = sideFor(from, to, specs.get(meta.semanticId)?.routeHints?.direction ?? 'auto'); const targetSide = opposite(sourceSide); edgeSides.set(edge.id, { sourceSide, targetSide }); for (const endpoint of [{ nodeId: meta.from, side: sourceSide, end: 'start', other: to }, { nodeId: meta.to, side: targetSide, end: 'end', other: from }]) { const key = `${endpoint.nodeId}:${endpoint.side}`; const list = groups.get(key) ?? []; list.push({ edge, ...endpoint }); groups.set(key, list); } }
  const offsets = new Map(); const used = new Map();
  for (const [key, list] of groups) { const side = key.slice(key.lastIndexOf(':') + 1); const verticalSide = side === 'left' || side === 'right'; list.sort((a, b) => { const ac = center(a.other); const bc = center(b.other); return (verticalSide ? ac.y - bc.y : ac.x - bc.x) || metaOf(a.edge).semanticId.localeCompare(metaOf(b.edge).semanticId); }); list.forEach((item, index) => { const offset = (index - (list.length - 1) / 2) * 16; const current = offsets.get(item.edge.id) ?? { start: 0, end: 0 }; current[item.end] = offset; offsets.set(item.edge.id, current); }); used.set(key, new Set(list.map((_, index) => (index - (list.length - 1) / 2) * 16))); }
  for (const edge of edges) { const meta = metaOf(edge); const from = nodes.get(meta.from); const to = nodes.get(meta.to); const sides = edgeSides.get(edge.id); if (!from || !to || !sides) continue; const fromCenter = center(from); const toCenter = center(to); const aligned = (['up','down'].includes(sides.sourceSide) && Math.abs(fromCenter.x - toCenter.x) <= 24) || (['left','right'].includes(sides.sourceSide) && Math.abs(fromCenter.y - toCenter.y) <= 24); if (!aligned) continue; const current = offsets.get(edge.id) ?? { start: 0, end: 0 }; const startKey = `${meta.from}:${sides.sourceSide}`; const endKey = `${meta.to}:${sides.targetSide}`; const startUsed = used.get(startKey) ?? new Set(); const endUsed = used.get(endKey) ?? new Set(); const candidates = [current.start, current.end, 0].filter((value, index, array) => array.indexOf(value) === index); const chosen = candidates.find((value) => (value === current.start || !startUsed.has(value)) && (value === current.end || !endUsed.has(value))); if (chosen !== undefined) { current.start = chosen; current.end = chosen; offsets.set(edge.id, current); } }
  return { offsets, edgeSides };
}
export function routeEdges(scene, spec = null) {
  const nodes = new Map(); const edges = []; for (const element of scene.elements ?? []) { const meta = metaOf(element); if (meta.role === 'node') nodes.set(meta.semanticId, element); if (meta.role === 'edge') edges.push(element); } if (nodes.size === 0) return scene;
  const specs = edgeSpecMap(spec); const primary = primaryPairs(spec); const { offsets, edgeSides } = unifiedPortOffsets(edges, nodes, specs); const bounds = sceneBounds(nodes);
  edges.sort((a, b) => { const am = metaOf(a); const bm = metaOf(b); const ap = specs.get(am.semanticId)?.routeHints?.priority === 'primary' || primary.has(`${am.from}->${am.to}`) ? 0 : 1; const bp = specs.get(bm.semanticId)?.routeHints?.priority === 'primary' || primary.has(`${bm.from}->${bm.to}`) ? 0 : 1; return ap - bp || am.semanticId.localeCompare(bm.semanticId); });
  const existingSegments = []; const channelUsage = new Map();
  for (const edge of edges) { const meta = metaOf(edge); const from = nodes.get(meta.from); const to = nodes.get(meta.to); if (!from || !to) continue; const sides = edgeSides.get(edge.id) ?? { sourceSide: sideFor(from, to), targetSide: opposite(sideFor(from, to)) }; const port = offsets.get(edge.id) ?? { start: 0, end: 0 }; const start = anchor(from, sides.sourceSide, port.start); const end = anchor(to, sides.targetSide, port.end); const channelKey = `${sides.sourceSide}:${Math.round((['right','left'].includes(sides.sourceSide) ? (start.x + end.x) / 2 : (start.y + end.y) / 2) / 40)}`; const laneIndex = channelUsage.get(channelKey) ?? 0; channelUsage.set(channelKey, laneIndex + 1); const laneOffset = laneIndex === 0 ? 0 : Math.ceil(laneIndex / 2) * 22 * (laneIndex % 2 === 1 ? 1 : -1); const obstacles = [...nodes.entries()].filter(([id]) => id !== meta.from && id !== meta.to).map(([, node]) => rectOf(node, 18)); const options = candidates(start, end, sides.sourceSide, sides.targetSide, bounds, laneOffset); options.sort((a, b) => compareScore(scoreRoute(a, obstacles, existingSegments), scoreRoute(b, obstacles, existingSegments))); const chosen = options[0] ?? [start, end]; edge.x = chosen[0].x; edge.y = chosen[0].y; edge.points = chosen.map((point) => [point.x - edge.x, point.y - edge.y]); const last = edge.points.at(-1); edge.width = last[0]; edge.height = last[1]; meta.route = { engine: 'graph-aware-v0.3.1', sourceSide: sides.sourceSide, targetSide: sides.targetSide, bends: Math.max(0, chosen.length - 2) }; existingSegments.push(...segmentsFromPoints(chosen)); }
  return scene;
}
function main() { const [scenePathArg, specPathArg, flag, outputPathArg] = process.argv.slice(2); if (!scenePathArg) { console.error('Usage: node src/route-edges.mjs <scene.excalidraw> [spec.json] [-o output.excalidraw]'); process.exit(1); } const scenePath = path.resolve(process.cwd(), scenePathArg); const specPath = specPathArg && specPathArg !== '-o' ? path.resolve(process.cwd(), specPathArg) : null; const actualFlag = specPath ? flag : specPathArg; const actualOutput = specPath ? outputPathArg : flag; const outputPath = actualFlag === '-o' && actualOutput ? path.resolve(process.cwd(), actualOutput) : scenePath; writeJson(outputPath, routeEdges(readJson(scenePath), specPath ? readJson(specPath) : null)); console.log(path.relative(process.cwd(), outputPath) || outputPath); }
const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url); if (isMain) { try { main(); } catch (error) { console.error(`route-edges failed: ${error instanceof Error ? error.message : String(error)}`); process.exit(1); } }
